{"name": "test_to_login", "status": "broken", "statusDetails": {"message": "RecursionError: maximum recursion depth exceeded", "trace": "self = <test.test_web.test_to_login.Test_HomePage object at 0x00000154056ACA60>\n\n    def test_to_login(self):\n        self.home_proxy.to_login()\n>       login_page_title = self.login_proxy.get_title()\n\ntest\\test_web\\test_to_login.py:23: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\npage\\login_page.py:33: in get_title\n    return self.login_handle.get_title_info()\npage\\login_page.py:26: in get_title_info\n    return self.get_text(self.get_title_info())\npage\\login_page.py:26: in get_title_info\n    return self.get_text(self.get_title_info())\nE   RecursionError: maximum recursion depth exceeded\n!!! Recursion detected (same locals & position)"}, "attachments": [{"name": "stdout", "source": "1f448286-cbee-4929-bf6b-4665ada1dd9f-attachment.txt", "type": "text/plain"}], "start": 1668533478226, "stop": 1668533478311, "uuid": "866b2707-913a-4ee3-a17f-dbddf8da292a", "historyId": "12ec9096dc2532553bb49276bea8f21d", "testCaseId": "fba31f286f30d766dc7244a52e88fd51", "fullName": "test.test_web.test_to_login.Test_HomePage#test_to_login", "labels": [{"name": "parentSuite", "value": "test.test_web"}, {"name": "suite", "value": "test_to_login"}, {"name": "subSuite", "value": "Test_HomePage"}, {"name": "host", "value": "xiaoma"}, {"name": "thread", "value": "7724-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test.test_web.test_to_login"}]}