{"name": "test_02_login[xiaoma@126.com-12345678-用户名或密码错误]", "status": "passed", "attachments": [{"name": "stdout", "source": "7e4cd948-80c4-4e80-93ae-ea3096ada50b-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "username", "value": "'xiaoma@126.com'"}, {"name": "password", "value": "12345678"}, {"name": "expected", "value": "'用户名或密码错误'"}], "start": 1668598940476, "stop": 1668598944684, "uuid": "e49ccd5a-9446-467d-9aed-e4a19f4cf689", "historyId": "7723dcf02c9d29bb9e36f44ad663994a", "testCaseId": "6a7e0c93f03755875413ec9c9508852b", "fullName": "test.test_web.test_login.Test_Login#test_02_login", "labels": [{"name": "parentSuite", "value": "test.test_web"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "Test_Login"}, {"name": "host", "value": "xiaoma"}, {"name": "thread", "value": "19844-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test.test_web.test_login"}]}