{"name": "test_02_login[xiaoma@126.com-12345678-用户名或密码错误]", "status": "passed", "attachments": [{"name": "stdout", "source": "4af0bfac-c1df-4b85-ae1f-9c090509ef31-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "username", "value": "'xiaoma@126.com'"}, {"name": "password", "value": "12345678"}, {"name": "expected", "value": "'用户名或密码错误'"}], "start": 1668756789088, "stop": 1668756793269, "uuid": "c3551aee-a559-473e-b7a8-f655417cd772", "historyId": "16fa590d1dd3f0a5bc1fe9bce4a1007f", "testCaseId": "6a7e0c93f03755875413ec9c9508852b", "fullName": "test.test_web.test_login.Test_Login#test_02_login", "labels": [{"name": "parentSuite", "value": "test.test_web"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "Test_Login"}, {"name": "host", "value": "xiaoma"}, {"name": "thread", "value": "10860-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test.test_web.test_login"}]}