{
  "uid" : "d19c317bceae7c8e",
  "name" : "test_02_login[xiaoma@126.com-12345678-用户名或密码错误]",
  "fullName" : "test.test_web.test_login.Test_Login#test_02_login",
  "historyId" : "16fa590d1dd3f0a5bc1fe9bce4a1007f",
  "time" : {
    "start" : 1668966971882,
    "stop" : 1668966976061,
    "duration" : 4179
  },
  "status" : "failed",
  "statusMessage" : "AssertionError: assert 0",
  "statusTrace" : "self = <test.test_web.test_login.Test_Login object at 0x000001E2D2C77400>\nusername = 'xiaoma@126.com', password = 12345678, expected = '用户名或密码错误'\n\n    @pytest.mark.parametrize(\"username, password, expected\",\n                             testcase[\"c_example\"])\n    def test_02_login(self, username, password, expected):\n        self.home_proxy.to_login()\n        time.sleep(2)\n        self.login_proxy.enter(username, password)\n        time.sleep(2)\n        loginErr_text = self.login_proxy.get_loginErr()\n        assert loginErr_text == expected\n>       assert 0\nE       assert 0\n\ntest\\test_web\\test_login.py:51: AssertionError",
  "flaky" : false,
  "beforeStages" : [ {
    "name" : "_xunit_setup_method_fixture_Test_Login",
    "time" : {
      "start" : 1668966970680,
      "stop" : 1668966971881,
      "duration" : 1201
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false,
    "stepsCount" : 0
  } ],
  "testStage" : {
    "status" : "failed",
    "statusMessage" : "AssertionError: assert 0",
    "statusTrace" : "self = <test.test_web.test_login.Test_Login object at 0x000001E2D2C77400>\nusername = 'xiaoma@126.com', password = 12345678, expected = '用户名或密码错误'\n\n    @pytest.mark.parametrize(\"username, password, expected\",\n                             testcase[\"c_example\"])\n    def test_02_login(self, username, password, expected):\n        self.home_proxy.to_login()\n        time.sleep(2)\n        self.login_proxy.enter(username, password)\n        time.sleep(2)\n        loginErr_text = self.login_proxy.get_loginErr()\n        assert loginErr_text == expected\n>       assert 0\nE       assert 0\n\ntest\\test_web\\test_login.py:51: AssertionError",
    "steps" : [ ],
    "attachments" : [ {
      "uid" : "473214baf7e46d47",
      "name" : "stdout",
      "source" : "473214baf7e46d47.txt",
      "type" : "text/plain",
      "size" : 78
    } ],
    "parameters" : [ ],
    "attachmentsCount" : 1,
    "shouldDisplayMessage" : true,
    "hasContent" : true,
    "stepsCount" : 0
  },
  "afterStages" : [ {
    "name" : "_xunit_setup_method_fixture_Test_Login::0",
    "time" : {
      "start" : 1668966976065,
      "stop" : 1668966978127,
      "duration" : 2062
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false,
    "stepsCount" : 0
  } ],
  "labels" : [ {
    "name" : "tag",
    "value" : "team('小马团队')"
  }, {
    "name" : "parentSuite",
    "value" : "test.test_web"
  }, {
    "name" : "suite",
    "value" : "test_login"
  }, {
    "name" : "subSuite",
    "value" : "Test_Login"
  }, {
    "name" : "host",
    "value" : "xiaoma"
  }, {
    "name" : "thread",
    "value" : "27768-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "test.test_web.test_login"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ {
    "name" : "expected",
    "value" : "'用户名或密码错误'"
  }, {
    "name" : "password",
    "value" : "12345678"
  }, {
    "name" : "username",
    "value" : "'xiaoma@126.com'"
  } ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ ],
    "categories" : [ {
      "name" : "Product defects",
      "matchedStatuses" : [ ],
      "flaky" : false
    } ],
    "tags" : [ "team('小马团队')" ]
  },
  "source" : "d19c317bceae7c8e.json",
  "parameterValues" : [ "'用户名或密码错误'", "12345678", "'xiaoma@126.com'" ]
}