self = <test.test_web.test_login.Test_Login object at 0x000001DDFE5C6C10>
username = 'xiaoma@126.com', password = 12345678, expected = '用户名或密码错误'

    @pytest.mark.parametrize("username, password, expected",
                             testcase["c_example"])
    def test_02_login(self, username, password, expected):
        self.home_proxy.to_login()
        time.sleep(2)
        self.login_proxy.enter(username, password)
        time.sleep(2)
        loginErr_text = self.login_proxy.get_loginErr()
        assert loginErr_text == expected
>       assert 0
E       assert 0

test\test_web\test_login.py:50: AssertionError